name: 'Builder'

on:
  push:
    branches:
    - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Upload an artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: src
        retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

    - name: Deploy the repo to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
